# Predefined users for authentication
# Format: username = "hashed_password"
[credentials]
admin = "240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9" # admin
charlesjsimpson = "8b45aa261a224e82cc911aae040c892fc5aacfbfc1ef3cbbbe72f0eb22d5bdfd" # your_password_hash

# Add any other configuration secrets here
[general]
app_name = "Hotel Financial Dashboard"
